name: Checkov Strict Scan

on:
  push:
  pull_request:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/aws
          framework: terraform
          soft_fail: false
          quiet: false
